spring.datasource.url=jdbc:mysql://localhost:3306/Parkifydb
spring.datasource.username=root
spring.datasource.password=Ya5in@astu##
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.address= 0.0.0.0
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_EMAIL}
spring.mail.password=${SMTP_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
